update
upgrade

tap caskroom/homebrew-cask

install brew-cask

# tools
install git
install mercurial
install zsh
install tmux
install vim --with-lua
install emacs --cocoa
install heroku-toolbelt
install reattach-to-user-namespace

# languages
install ghc
cask install java
install scala
install go --cross-compile-common
install node

# tools related to languages
# for objective-caml
cask install xquartz
install ssreflect
install opam

# casks
cask install google-chrome
cask install google-japanese-ime
cask install bettertouchtool
cask install dropbox
cask install copy
cask install virtualbox
cask install vagrant
cask install mendeley-desktop
cask install skim
cask install lyn
cask install libreoffice
cask install kobito
cask install alfred
cask alfred link
cask install mactex
cask install iterm2
cask install dash
cask install sourcetree
cask install slack
