#!/usr/bin/env zsh

case "$1" in
    "compile" | "make")
        if [ "${2}" = "" ]; then
            num_files=`ls | grep '\.tex$' | wc -l`
            if [ $num_files -eq 1 ]; then
                filename=`ls | grep '\.tex$'`
                echo "Compile ${filename}"
                echo ""
                filename=`basename ${filename} .tex`
                platex ${filename}.tex && dvipdfmx ${filename}.dvi
            else
                echo "more than 1 LaTeX files found."
                ls | grep '\.tex$'
                echo "Please specify the LaTeX filename."
                echo "e.g., tex ${1} report.tex"
            fi
        else
            filename=`basename ${2} .tex`
            platex ${filename}.tex && dvipdfmx ${filename}.dvi
        fi
        ;;
    "clean")
        dir=${2}
        if [ "$dir" = "" ]; then
            dir="."
        fi
        find -E $dir -regex '.*\.(aux|dvi|log)'
        echo -n "These would be removed. ok? [y/n] "
        read ok
        if [ "$ok" = "y" ]; then
            find -E $dir -regex '.*\.(aux|dvi|log)' | xargs rm
            echo "done."
        fi
        ;;
    *)
        echo "LaTeX utility"
        echo ""
        echo "Usage: tex <command>"
        echo ""
        echo "Commands:"
        echo "  compile <filename>    compile TeX file to pdf"
        echo "  make    <filename>    equivalent to compile command"
        echo "  clean   <path>        remove *.dvi *.log *.aux"
esac
